# Minimal use-case examples of pcb4ec
from pcb4ec import session

ex1 = """
#-------------------------------------------------------------------------
# 1: START SESSION WITH DEFAULT CONFIGURATION
#-------------------------------------------------------------------------
"""
print(ex1)
# 1.1 Start session after connecting the device to the USB port;
# the user will be asked to select a port from a list of detected ports.
ss1 = session()
# 1.2 Use the read method to read the temperature channel
value = ss1.read('TEMP')
print(value)
# 1.3 Get the channel identifiers
ss1.read()
# 1.4 Make an aquisition with standard defaults
data = ss1()
print(data)
# 1.5 Make a second acquisition and check aquisition journal
ss1()
print(ss1.acquisition)

ex2 = """
#-------------------------------------------------------------------------
# 2: SESSION WITH CUSTOM CONFIGURATIONS EXAMPLE
#-------------------------------------------------------------------------
"""
print(ex2)
# 2.1 Silently start session with known device_port 
ss2 = session(device_port='/dev/ttyUSB0', verbose=False)
# 2.2 Acquisition with custom channel list and settings + write to file (autogenerated)
d = ss2(['ISE1', 'ISE2', 'TEMP'], verbose=True, nacquisitions=5, timestep=2.5, file=True)
print(d)
print('CSV file created in folder')
# 2.3 Change PCB physical settigs, e.g. by adding a 20k resistor to IA RES socket
ss2.physical_settings(RIA_socket=20e3)
# 2.4 Acquisition with custom settings + write to file
print('Starting now a silent acquisition')
d2 = ss2('ALL', verbose=False, nacquisitions=10, timestep=.5, file='myscript-acquisition-example.txt')
print('Silent acquisition ended. Check "myscript-acquisition-example.txt" in folder')
